### ISSUE TITLE
Web Trigger "Learn More" Link Not Working

### ISSUE THREAD

**Issue by Klflanigan2** [RestComm/visual-designer#1]
When you click on "Learn More" under the Web Trigger, the site cannot be found. 
![notfound](https://cloud.githubusercontent.com/assets/23537321/22831607/97e84236-ef70-11e6-8e74-93ff3dd517ee.PNG)
![webtriggermodal](https://cloud.githubusercontent.com/assets/23537321/22831611/9c2d9d50-ef70-11e6-9e42-545d07cf3fb2.PNG)

**Comment by deruelle** [comment]
Thanks @Klflanigan2 for reporting the issue. 

@otsakir It seems like the link should be  http://documentation.telestax.com/connect/rvd/Restcomm%20RVD%20-%20Using%20Web%20Trigger.html#web-trigger instead of http://documentation.telestax.com/connect/rvd/Restcomm%20RVD%20-%20Using%20Web%20Trigger/.html#web-trigger
