### ISSUE TITLE
RVD shouldn't allow creating projects with same name

### ISSUE THREAD

**Issue by FerUy** [RestComm/visual-designer#126]
See image attached.
![2017_04_21_13_45_03_restcomm_designer_same_name_projects](https://cloud.githubusercontent.com/assets/14883482/25269123/f593fa74-2698-11e7-8d71-87fefb10ca3e.png)

**Comment by otsakir** [comment]
@FerUy , it seems that we're dealing with a 'wrong feature' not a bug. Since the underllying app SID is different for the two projects, the underlying layer works right.

If _same project creation_ is to be prevented, IMO this should be just a convenient restriction in RVD and the Restcomm applications API (i.e. using the REST API applications with the same FriendlyName like `Project_1` should be allowed to be created). A 'search' method/parameter of the Application endpoint could help here as it would allow checking for the existence of an application named 'Project_1' before creating/renaming it.

I could also use an opinion from @gvagenas on that (i.e. supporting search-by-FriendlyName in the Applicaiton endpoint).

**Comment by otsakir** [comment]
Quoting @gvagenas:

> @otsakir we came across the same issue in the past, before we move to applications. I agree we can support search by friendly name to help on this restriction
